input_dir: ../App/TripCheck/Resources/
output_dir: ../App/TripCheck/Generated/
strings:
  - inputs: Strings.strings
    outputs:
      - templateName: structured-swift5
        output: Strings.swift
        params:
          enumName: Strings
  - inputs: Base.lproj
    filter: .+\.strings$
    outputs:
      - templateName: structured-swift5
        output: Localizable.swift
        params:
          enumName: Localizable
                    
xcassets:
  inputs: Assets.xcassets
  outputs:
    - templatePath: Templates/swiftui-xcassets-template.stencil
      output: Assets.swift
      params:
        enumName: Assets
fonts:
  inputs: Fonts
  outputs:
    templatePath: Templates/fonts_swift5_swiftui.stencil
    output: Fonts.swift

